### PR TITLE
RAND-219 - Amend dockerfile and tiltfile to work with buildkit

### PR DESCRIPTION
**Pull request by JoelClemence**
* Unfortunatelyd despite four years passing the downstream moby issue which this relates to has not been fixed therefore this is a workaround

### CODE REVIEW

**Review by ch-tstrickland — COMMENTED** [review]
If this works, then great. Is this really all that we need to do??

**Review by bcullerton — COMMENTED** [review]
Minor point and can definitely be separated from this but the golang base pipeline commits to both eu-west-1 and eu-west-2. Might be a good opportunity to move over to London in a big pile of Dockerfiles?

**Comment by JoelClemence** [comment]
> Minor point and can definitely be separated from this but the golang base pipeline commits to both eu-west-1 and eu-west-2. Might be a good opportunity to move over to London in a big pile of Dockerfiles?

Possibly, does the registry exist in eu-west-2 and will the new image be pushed there?

**Comment by bcullerton** [comment]
https://ci.platform.aws.chdev.org/teams/team-platform/pipelines/ci-golang-build/jobs/build-image-1.19/builds/5

Yep, the pipeline for 1.19 pushes to both

**Comment by bcullerton** [comment]
Copied the wrong pipeline in my previous reply. The pipeline does try to push to eu-west-2 as well for the golang image, it should be usable once the base is merged in:
https://ci.platform.aws.chdev.org/teams/common/pipelines/docker-base-images/jobs/golang-builder-build-image/builds/5

**Comment by JoelClemence** [comment]
@bcullerton - ok I have changed and tested locally - it was able to pull image down :)

**Review by bcullerton — DISMISSED** [review]

**Comment by JoelClemence** [comment]
PR #15 changes the region to eu-west-2

**Review by bcullerton — APPROVED** [review]

**Pull request merged**
